
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
  name: sample-rabbitmq-app
  namespace: #@ data.values.namespace
spec:
  params:
  - name: tekton-pipeline-name
    value: developer-defined-tekton-pipeline
  serviceClaims:
  - name: rabbitmq
    ref:
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      name: sample-rabbitmq-app-cluster
  - name: sso
    ref:
      apiVersion: v1
      kind: Secret
      name: sample-rabbitmq-app-registration-manual
  source:
    git:
      ref:
        branch: add-security
      url: https://github.com/voor/rabbitmq-sample.git
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: sample-rabbitmq-app-cluster
  namespace: #@ data.values.namespace
---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: ClientRegistration
metadata:
  name: sample-rabbitmq-app-registration
  namespace: #@ data.values.namespace
spec:
  redirectURIs:
    - #@ "https://sample-rabbitmq-app.{}.{}/login/oauth2/code/sso".format(data.values.namespace, data.values.domain)
    - "http://127.0.0.1:8080/login/oauth2/code/sso"
  requireUserConsent: false
  clientAuthenticationMethod: basic
  authorizationGrantTypes:
    - "refresh_token"
    - "authorization_code"
  scopes:
    - name: "openid"
      description: "To indicate that the application intends to use OIDC to verify the user's identity"
    - name: "email"
      description: "The user's email"
    - name: "profile"
      description: "The user's profile information"